import { createContext, useContext, useState, useCallback } from 'react';

const translations = {
  en: {
    // Nav
    dashboard: 'Dashboard', workouts: 'Workouts', meals: 'Meals',
    weight: 'Weight', coach: 'AI Coach', calendar: 'Calendar', settings: 'Settings',
    // Page subtitles
    dashSub: 'Your fitness overview at a glance',
    workoutsSub: 'Log and track your exercises',
    mealsSub: 'Track your daily nutrition',
    weightSub: 'Track your weight and body measurements',
    coachSub: 'Personalized advice powered by Claude AI',
    calendarSub: 'View your training and nutrition history',
    settingsSub: 'Manage your account and preferences',
    // Common
    save: 'Save', cancel: 'Cancel', delete: 'Delete', edit: 'Edit',
    add: 'Add', close: 'Close', today: 'Today', send: 'Send',
    logOut: 'Log Out', exportData: 'Export Data', clearChat: 'Clear Chat',
    // Settings
    profile: 'Profile', displayName: 'Display Name', email: 'Email',
    changePassword: 'Change Password', currentPassword: 'Current Password',
    newPassword: 'New Password', confirmPassword: 'Confirm New Password',
    preferences: 'Preferences', language: 'Language', units: 'Units',
    theme: 'Theme', dark: 'Dark', light: 'Light',
    notifications: 'Notifications',
    mealReminder: 'Meal logging reminder',
    workoutReminder: 'Workout logging reminder',
    yourData: 'Your Data', exportAllData: 'Export all your data as JSON',
    account: 'Account', signOut: 'Sign out of your account',
    deleteAccount: 'Permanently delete your account and all data',
    typeDelete: 'Type DELETE to confirm:',
    profilePhoto: 'Profile Photo', uploadPhoto: 'Upload', removePhoto: 'Remove',
    // Meals
    food: 'Food', calories: 'Calories', protein: 'Protein',
    carbs: 'Carbs', fat: 'Fat', servings: 'Servings',
    searchFood: 'Search food...', quickAdd: 'Quick Add',
    repeatYesterday: 'Repeat Yesterday', favourites: 'Favourites',
    // Workouts
    exercise: 'Exercise', sets: 'Sets', reps: 'Reps',
    restTimer: 'Rest Timer', templates: 'Templates', volume: 'Volume',
    // Weight
    goalWeight: 'Goal Weight', weeklyAvg: 'Weekly Averages',
    measurements: 'Measurements', waist: 'Waist', chest: 'Chest',
    arms: 'Arms', hips: 'Hips', thighs: 'Thighs',
    // Calendar
    month: 'Month', week: 'Week', streak: 'Streak',
    restDay: 'Rest day', noActivity: 'No activity recorded on this day.',
    // Coach
    askCoach: 'Ask your coach anything...',
    coachBanner: 'I can see your meals, workouts, weight, and goals. Ask me anything and I\'ll give advice based on your actual data.',
    // Onboarding
    onboardWelcome: 'Welcome to Nexero!',
    onboardGoals: 'Your Goals',
    onboardPlan: 'Your Plan',
    // Dashboard
    dayStreak: 'Day Streak', volumeKg: 'Volume kg', kcalToday: 'Kcal Today',
    kcalLeft: 'Kcal Left', proteinToday: 'Protein Today', logMeal: 'Log Meal',
    eaten: 'Eaten', target: 'Target', remaining: 'Remaining',
    thisWeek: 'This Week', sessions: 'sessions',
    weeklyCalorieTrend: 'Weekly Calorie Trend', fullHistory: 'Full History',
    activity: 'Activity',
    todaysMacros: "Today's Macros", personalRecords: 'Personal Records',
    allPrs: 'All PRs', logWorkout: 'Log Workout',
    recentWorkouts: 'Recent Workouts', viewAll: 'View All',
    recentMeals: 'Recent Meals', noPrsYet: 'No PRs yet. Start logging workouts!',
    noWorkoutsYet: 'No workouts yet. Start tracking!',
    noMealsYet: 'No meals logged. Start tracking!',
    // Workouts detail
    exerciseLibrary: 'Exercise Library', searchExercises: 'Search exercises...',
    newWorkout: 'New Workout', addToSession: 'Add to Session',
    start: 'Start', stop: 'Stop', saveSession: 'Save Session',
    sessionLog: 'Session Log', noExercisesToday: 'No exercises logged today. Pick one from the library!',
    volumeProgression: 'Volume Progression', selectExercise: 'Select an exercise...',
    allWorkouts: 'All Workouts', date: 'Date',
    logMoreDays: 'Log this exercise on more days to see trends.',
    // Weight detail
    logWeight: 'Log Weight', current: 'Current', change: 'Change',
    entries: 'Entries', weightProgress: 'Weight Progress',
    bodyMeasurements: 'Body Measurements', logMeasurements: '+ Log Measurements',
    saveMeasurements: 'Save Measurements', noWeightYet: 'No weight entries yet',
    noMeasurementsYet: 'No measurements yet',
    trackBody: 'Track your waist, chest, arms, and more to see your body composition change.',
    // Coach detail
    you: 'You', aiCoach: 'AI Coach', chatCleared: 'Chat cleared!',
    coachGreeting: 'Hey! I\'m your AI fitness coach powered by Claude. I can see your logged meals, workouts, and goals — ask me anything and I\'ll give you personalized advice!\n\nTry: "What should I eat to hit my macros?" or "Rate my workout today"',
    coachGreetingFallback: 'Hey! I\'m your AI fitness coach. Ask me anything about training, nutrition, or recovery!',
    coachClearedMsg: 'Chat cleared! Ask me anything — I still have access to all your logged data.',
    coachErrorMsg: 'Sorry, something went wrong. Please try again.',
    coachNoResponse: 'Sorry, I couldn\'t generate a response.',
  },
  de: {
    dashboard: 'Dashboard', workouts: 'Training', meals: 'Mahlzeiten',
    weight: 'Gewicht', coach: 'KI-Coach', calendar: 'Kalender', settings: 'Einstellungen',
    dashSub: 'Dein Fitness-\u00dcberblick auf einen Blick',
    workoutsSub: '\u00dcbungen protokollieren und verfolgen',
    mealsSub: 'Deine t\u00e4gliche Ern\u00e4hrung verfolgen',
    weightSub: 'Gewicht und K\u00f6rperma\u00dfe verfolgen',
    coachSub: 'Personalisierte Beratung mit Claude KI',
    calendarSub: 'Trainings- und Ern\u00e4hrungshistorie ansehen',
    settingsSub: 'Konto und Einstellungen verwalten',
    save: 'Speichern', cancel: 'Abbrechen', delete: 'L\u00f6schen', edit: 'Bearbeiten',
    add: 'Hinzuf\u00fcgen', close: 'Schlie\u00dfen', today: 'Heute', send: 'Senden',
    logOut: 'Abmelden', exportData: 'Daten exportieren', clearChat: 'Chat l\u00f6schen',
    profile: 'Profil', displayName: 'Anzeigename', email: 'E-Mail',
    changePassword: 'Passwort \u00e4ndern', currentPassword: 'Aktuelles Passwort',
    newPassword: 'Neues Passwort', confirmPassword: 'Neues Passwort best\u00e4tigen',
    preferences: 'Einstellungen', language: 'Sprache', units: 'Einheiten',
    theme: 'Design', dark: 'Dunkel', light: 'Hell',
    notifications: 'Benachrichtigungen',
    mealReminder: 'Erinnerung Mahlzeiten erfassen',
    workoutReminder: 'Erinnerung Training erfassen',
    yourData: 'Deine Daten', exportAllData: 'Alle Daten als JSON exportieren',
    account: 'Konto', signOut: 'Von deinem Konto abmelden',
    deleteAccount: 'Konto und alle Daten dauerhaft l\u00f6schen',
    typeDelete: 'Tippe DELETE zum Best\u00e4tigen:',
    profilePhoto: 'Profilfoto', uploadPhoto: 'Hochladen', removePhoto: 'Entfernen',
    food: 'Essen', calories: 'Kalorien', protein: 'Protein',
    carbs: 'Kohlenhydrate', fat: 'Fett', servings: 'Portionen',
    searchFood: 'Essen suchen...', quickAdd: 'Schnell hinzuf\u00fcgen',
    repeatYesterday: 'Gestern wiederholen', favourites: 'Favoriten',
    exercise: '\u00dcbung', sets: 'S\u00e4tze', reps: 'Wiederholungen',
    restTimer: 'Pausentimer', templates: 'Vorlagen', volume: 'Volumen',
    goalWeight: 'Zielgewicht', weeklyAvg: 'Wochendurchschnitt',
    measurements: 'K\u00f6rperma\u00dfe', waist: 'Taille', chest: 'Brust',
    arms: 'Arme', hips: 'H\u00fcfte', thighs: 'Oberschenkel',
    month: 'Monat', week: 'Woche', streak: 'Serie',
    restDay: 'Ruhetag', noActivity: 'Keine Aktivit\u00e4t an diesem Tag.',
    askCoach: 'Frag deinen Coach...',
    coachBanner: 'Ich kann deine Mahlzeiten, Trainings, Gewicht und Ziele sehen. Frag mich und ich gebe Ratschl\u00e4ge basierend auf deinen Daten.',
    onboardWelcome: 'Willkommen bei Nexero!',
    onboardGoals: 'Deine Ziele',
    onboardPlan: 'Dein Plan',
    dayStreak: 'Tages-Serie', volumeKg: 'Volumen kg', kcalToday: 'Kcal heute',
    kcalLeft: 'Kcal \u00fcbrig', proteinToday: 'Protein heute', logMeal: 'Mahlzeit erfassen',
    eaten: 'Gegessen', target: 'Ziel', remaining: 'Verbleibend',
    thisWeek: 'Diese Woche', sessions: 'Einheiten',
    weeklyCalorieTrend: 'Wochen-Kalorien-Trend', fullHistory: 'Gesamtverlauf',
    activity: 'Aktivit\u00e4t',
    todaysMacros: 'Heutige Makros', personalRecords: 'Bestleistungen',
    allPrs: 'Alle PRs', logWorkout: 'Training erfassen',
    recentWorkouts: 'Letzte Trainings', viewAll: 'Alle anzeigen',
    recentMeals: 'Letzte Mahlzeiten', noPrsYet: 'Noch keine PRs. Starte mit dem Training!',
    noWorkoutsYet: 'Noch keine Trainings. Starte jetzt!',
    noMealsYet: 'Keine Mahlzeiten erfasst. Starte jetzt!',
    exerciseLibrary: '\u00dcbungsbibliothek', searchExercises: '\u00dcbungen suchen...',
    newWorkout: 'Neues Training', addToSession: 'Zur Einheit hinzuf\u00fcgen',
    start: 'Start', stop: 'Stopp', saveSession: 'Einheit speichern',
    sessionLog: 'Einheits-Protokoll', noExercisesToday: 'Heute noch keine \u00dcbungen. W\u00e4hle eine aus der Bibliothek!',
    volumeProgression: 'Volumen-Verlauf', selectExercise: '\u00dcbung ausw\u00e4hlen...',
    allWorkouts: 'Alle Trainings', date: 'Datum',
    logMoreDays: 'Logge diese \u00dcbung an mehr Tagen f\u00fcr Trends.',
    logWeight: 'Gewicht erfassen', current: 'Aktuell', change: 'Ver\u00e4nderung',
    entries: 'Eintr\u00e4ge', weightProgress: 'Gewichtsverlauf',
    bodyMeasurements: 'K\u00f6rperma\u00dfe', logMeasurements: '+ Ma\u00dfe erfassen',
    saveMeasurements: 'Ma\u00dfe speichern', noWeightYet: 'Noch keine Gewichtseintr\u00e4ge',
    noMeasurementsYet: 'Noch keine Ma\u00dfe',
    trackBody: 'Verfolge Taille, Brust, Arme und mehr.',
    you: 'Du', aiCoach: 'KI-Coach', chatCleared: 'Chat gel\u00f6scht!',
    coachGreeting: 'Hey! Ich bin dein KI-Fitness-Coach, angetrieben von Claude. Ich sehe deine erfassten Mahlzeiten, Trainings und Ziele \u2014 frag mich alles und ich gebe dir pers\u00f6nliche Ratschl\u00e4ge!\n\nVersuche: "Was soll ich essen, um meine Makros zu erreichen?" oder "Bewerte mein heutiges Training"',
    coachGreetingFallback: 'Hey! Ich bin dein KI-Fitness-Coach. Frag mich alles \u00fcber Training, Ern\u00e4hrung oder Erholung!',
    coachClearedMsg: 'Chat gel\u00f6scht! Frag mich alles \u2014 ich habe weiterhin Zugriff auf deine Daten.',
    coachErrorMsg: 'Entschuldigung, etwas ist schief gelaufen. Bitte versuche es erneut.',
    coachNoResponse: 'Entschuldigung, ich konnte keine Antwort generieren.',
  },
  fr: {
    dashboard: 'Tableau de bord', workouts: 'Entra\u00eenements', meals: 'Repas',
    weight: 'Poids', coach: 'Coach IA', calendar: 'Calendrier', settings: 'Param\u00e8tres',
    dashSub: 'Votre aper\u00e7u fitness en un coup d\u2019\u0153il',
    workoutsSub: 'Enregistrez et suivez vos exercices',
    mealsSub: 'Suivez votre nutrition quotidienne',
    weightSub: 'Suivez votre poids et mensurations',
    coachSub: 'Conseils personnalis\u00e9s par Claude IA',
    calendarSub: 'Voir l\u2019historique entra\u00eenement et nutrition',
    settingsSub: 'G\u00e9rez votre compte et pr\u00e9f\u00e9rences',
    save: 'Enregistrer', cancel: 'Annuler', delete: 'Supprimer', edit: 'Modifier',
    add: 'Ajouter', close: 'Fermer', today: 'Aujourd\u2019hui', send: 'Envoyer',
    logOut: 'D\u00e9connexion', exportData: 'Exporter', clearChat: 'Effacer le chat',
    profile: 'Profil', displayName: 'Nom affich\u00e9', email: 'E-mail',
    changePassword: 'Changer le mot de passe', currentPassword: 'Mot de passe actuel',
    newPassword: 'Nouveau mot de passe', confirmPassword: 'Confirmer le mot de passe',
    preferences: 'Pr\u00e9f\u00e9rences', language: 'Langue', units: 'Unit\u00e9s',
    theme: 'Th\u00e8me', dark: 'Sombre', light: 'Clair',
    notifications: 'Notifications',
    mealReminder: 'Rappel saisie des repas',
    workoutReminder: 'Rappel saisie des entra\u00eenements',
    yourData: 'Vos donn\u00e9es', exportAllData: 'Exporter toutes vos donn\u00e9es en JSON',
    account: 'Compte', signOut: 'Se d\u00e9connecter de votre compte',
    deleteAccount: 'Supprimer d\u00e9finitivement votre compte et donn\u00e9es',
    typeDelete: 'Tapez DELETE pour confirmer :',
    profilePhoto: 'Photo de profil', uploadPhoto: 'T\u00e9l\u00e9charger', removePhoto: 'Supprimer',
    food: 'Aliment', calories: 'Calories', protein: 'Prot\u00e9ines',
    carbs: 'Glucides', fat: 'Lipides', servings: 'Portions',
    searchFood: 'Chercher un aliment...', quickAdd: 'Ajout rapide',
    repeatYesterday: 'R\u00e9p\u00e9ter hier', favourites: 'Favoris',
    exercise: 'Exercice', sets: 'S\u00e9ries', reps: 'R\u00e9p\u00e9titions',
    restTimer: 'Minuteur repos', templates: 'Mod\u00e8les', volume: 'Volume',
    goalWeight: 'Poids cible', weeklyAvg: 'Moyennes hebdomadaires',
    measurements: 'Mensurations', waist: 'Taille', chest: 'Poitrine',
    arms: 'Bras', hips: 'Hanches', thighs: 'Cuisses',
    month: 'Mois', week: 'Semaine', streak: 'S\u00e9rie',
    restDay: 'Jour de repos', noActivity: 'Aucune activit\u00e9 enregistr\u00e9e ce jour.',
    askCoach: 'Posez votre question au coach...',
    coachBanner: 'Je vois vos repas, entra\u00eenements, poids et objectifs. Posez-moi une question et je vous donnerai des conseils bas\u00e9s sur vos donn\u00e9es.',
    onboardWelcome: 'Bienvenue sur Nexero !',
    onboardGoals: 'Vos Objectifs',
    onboardPlan: 'Votre Plan',
    dayStreak: 'Jours cons\u00e9cutifs', volumeKg: 'Volume kg', kcalToday: 'Kcal aujourd\u2019hui',
    kcalLeft: 'Kcal restantes', proteinToday: 'Prot\u00e9ines aujourd\u2019hui', logMeal: 'Enregistrer repas',
    eaten: 'Consomm\u00e9', target: 'Objectif', remaining: 'Restant',
    thisWeek: 'Cette semaine', sessions: 's\u00e9ances',
    weeklyCalorieTrend: 'Tendance calorique hebdo', fullHistory: 'Historique complet',
    activity: 'Activit\u00e9',
    todaysMacros: 'Macros du jour', personalRecords: 'Records personnels',
    allPrs: 'Tous les PRs', logWorkout: 'Enregistrer entra\u00eenement',
    recentWorkouts: 'Entra\u00eenements r\u00e9cents', viewAll: 'Tout voir',
    recentMeals: 'Repas r\u00e9cents', noPrsYet: 'Pas encore de PRs. Commencez \u00e0 vous entra\u00eener !',
    noWorkoutsYet: 'Pas encore d\u2019entra\u00eenements. Commencez !',
    noMealsYet: 'Aucun repas enregistr\u00e9. Commencez !',
    exerciseLibrary: 'Biblioth\u00e8que d\u2019exercices', searchExercises: 'Chercher des exercices...',
    newWorkout: 'Nouvel entra\u00eenement', addToSession: 'Ajouter \u00e0 la s\u00e9ance',
    start: 'D\u00e9marrer', stop: 'Arr\u00eater', saveSession: 'Sauver la s\u00e9ance',
    sessionLog: 'Journal de s\u00e9ance', noExercisesToday: 'Aucun exercice aujourd\u2019hui. Choisissez-en un !',
    volumeProgression: 'Progression du volume', selectExercise: 'Choisir un exercice...',
    allWorkouts: 'Tous les entra\u00eenements', date: 'Date',
    logMoreDays: 'Enregistrez cet exercice plus souvent pour voir les tendances.',
    logWeight: 'Enregistrer poids', current: 'Actuel', change: 'Variation',
    entries: 'Entr\u00e9es', weightProgress: 'Progression du poids',
    bodyMeasurements: 'Mensurations', logMeasurements: '+ Enregistrer mensurations',
    saveMeasurements: 'Sauver mensurations', noWeightYet: 'Pas encore d\u2019entr\u00e9es de poids',
    noMeasurementsYet: 'Pas encore de mensurations',
    trackBody: 'Suivez taille, poitrine, bras et plus.',
    you: 'Vous', aiCoach: 'Coach IA', chatCleared: 'Chat effac\u00e9 !',
    coachGreeting: 'Salut ! Je suis votre coach fitness IA propuls\u00e9 par Claude. Je vois vos repas, entra\u00eenements et objectifs \u2014 posez-moi une question et je vous donnerai des conseils personnalis\u00e9s !\n\nEssayez : "Que manger pour atteindre mes macros ?" ou "\u00c9value mon entra\u00eenement du jour"',
    coachGreetingFallback: 'Salut ! Je suis votre coach fitness IA. Posez-moi une question sur l\'entra\u00eenement, la nutrition ou la r\u00e9cup\u00e9ration !',
    coachClearedMsg: 'Chat effac\u00e9 ! Posez-moi une question \u2014 j\'ai toujours acc\u00e8s \u00e0 vos donn\u00e9es.',
    coachErrorMsg: 'D\u00e9sol\u00e9, une erreur s\'est produite. Veuillez r\u00e9essayer.',
    coachNoResponse: 'D\u00e9sol\u00e9, je n\'ai pas pu g\u00e9n\u00e9rer de r\u00e9ponse.',
  },
};

const LangContext = createContext(null);

export function LangProvider({ children }) {
  const [lang, setLangState] = useState(() => localStorage.getItem('lang') || 'en');

  const setLang = (l) => { setLangState(l); localStorage.setItem('lang', l); };
  const t = useCallback((key) => translations[lang]?.[key] || translations.en[key] || key, [lang]);

  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext);
